apiVersion: apps/v1
kind: Deployment
metadata:
  name: role-service
  namespace: role-prod
  labels:
    app: role-service
    type: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: role-service
  template:
    metadata:
      labels:
        app: role-service
    spec:
      containers:
      - name: role-service
        image: lordblackfish/role-service:version-number
        ports:
        - containerPort: 80
