apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
<<<<<<< HEAD
  name: role-ingress-prod
  namespace: role-prod
=======
  name: "role-ingress"
  namespace: role-prod

>>>>>>> 8486a5486a31b3ad9afa49d8ae23439982393487
spec:
  rules:
    - host:
      http:
        paths:
          - path: /role
            backend:
              serviceName: role-service
              servicePort: 80
