apiVersion: v1
kind: Service
metadata:
  name: role-service
<<<<<<< HEAD
  namespace: role-test
=======
  namespace: role-dev
>>>>>>> dev
spec:
  type: NodePort
  selector:
    app: role-service
  ports:
    - port: 80
      targetPort: 80
