pipeline {
  agent {
    docker {
      image 'lordblackfish/beta-env'
      args "--entrypoint=''"
    }
  }
  environment {
    DOCKER_NAMESPACE = 'rahafog1'
    SERVICE_NAME = 'office-service'
   }
   stages {
      stage("test") {
          steps {
             
            dir(env.SERVICE_NAME) {
            script {

                def strCount = sh(returnStdout: true, script: "git diff --name-only ${env.GIT_COMMIT} ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT} | grep ${env.SERVICE_NAME} | wc -l").trim()
                if(strCount=="0") {
                    echo "Skipping build no files updated"
                    CONTINUE_BUILD = false
                } else {
                    echo "Changes found!!! build"
                    CONTINUE_BUILD = true
                }
            }
        }
              
          }
      }
      stage("Release") {
               when { environment name: 'CONTINUE_BUILD', value: 'ture' } 
		steps {
                  sh '''
                      env
                      echo build
                  '''
              }
          
      }
  }
}
