pipeline {
  agent {
    docker {
      image 'lordblackfish/beta-env'
      args "--entrypoint=''"
    }
  }
  environment {
    DOCKER_NAMESPACE = 'rahafog1'
    SERVICE_NAME = 'office-service'
   }
   stages {
      stage("test") {
          steps {
             
            dir(env.SERVICE_NAME) {
	    sh '''
               DIFF=$(git diff --name-only $GIT_COMMIT $GIT_PREVIOUS_SUCCESSFUL_COMMIT | grep $SERVICE_NAME | wc -l)
               if [[ $DIFF -gt 0 ]]
               then
                echo 'detcted changes, proceeding with build'
                export CONTINUE_BUILD=true
               else
	        echo 'no detcted changes, skipping build'
                export CONTINUE_BUILD=false
               fi
	    '''
           /* script {

                def strCount = sh(returnStdout: true, script: "git diff --name-only ${env.GIT_COMMIT} ${env.GIT_PREVIOUS_SUCCESSFUL_COMMIT} | grep ${env.SERVICE_NAME} | wc -l").trim()
                if(strCount=="0") {
                    echo "Skipping build no files updated"
                    env.CONTINUE_BUILD = false
                } else {
                    echo "Changes found!!! build"
                    env.CONTINUE_BUILD = true
                }
            }*/
        }
              
          }
      }
      stage("Release") {
               when { environment name: 'CONTINUE_BUILD', value: 'true' } 
		steps {
                  sh '''
                      env
                      echo build
                  '''
              }
          
      }
  }
}
