apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: department-ingress-prod
  namespace: department-prod
spec:
  rules:
    - host:
      http:
        paths:
          - path: /department
            backend:
              serviceName: department-service
              servicePort: 80
