apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "project-assessment-ingress"
  namespace: project-test

spec:
  rules:
    - host:
      http:
        paths:
          - path: /project
            backend:
              serviceName: project-assessment-site
              servicePort: 80
