apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: assessment-ingress-prod
  namespace: 

spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            backend:
              serviceName: assessment-service
              servicePort: 80
