apiVersion: v1
kind: Service
metadata:
  name: project-assessment-site
<<<<<<< HEAD
  namespace: project-test
=======
  namespace: project-dev
>>>>>>> dev
spec:
  type: NodePort
  selector:
    app: project-assessment-site
  ports:
    - port: 80
      targetPort: 80
